config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :surveys

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def new
	end

	def show
    @survey = Survey.find(params[:id])
  	end
  	
	def create
		@survey = Survey.new(survey_params)
 
  		@survey.save
  		redirect_to @survey
	end
	private
  		def survey_params
    		params.require(:survey).permit(:title, :text)
  		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataCollection</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/new.html.erb
<%= form_with scope: :survey, url: surveys_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/surveys/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @survey.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @survey.text %>
</p>
 
<%= link_to 'Back', new_survey_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>